"""create user_preferences, user_goals e reading_history

Revision ID: d12024f6ddd4
Revises: fd60707d073d
Create Date: 2026-08-04 19:42:02.838129

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd12024f6ddd4'
down_revision: str | Sequence[str] | None = 'fd60707d073d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('LENDO', 'CONCLUIDO', 'ABANDONADO', name='status_leitura_enum'), nullable=False),
    sa.Column('feedback', sa.Enum('GOSTOU', 'NAO_GOSTOU', 'NEUTRO', name='feedback_leitura_enum'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('objetivo', sa.String(length=255), nullable=False),
    sa.Column('nivel_conhecimento', sa.Enum('INICIANTE', 'INTERMEDIARIO', 'AVANCADO', name='nivelconhecimento'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('tempo_disponivel_semanal', sa.Integer(), nullable=True))
    op.drop_column('users', 'tempo_disponivel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tempo_disponivel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'tempo_disponivel_semanal')
    op.drop_table('user_preferences')
    op.drop_table('user_goals')
    op.drop_table('reading_history')
    # ### end Alembic commands ###
